### ISSUE TITLE
Imágenes múltiples

### ISSUE THREAD

**Issue by Luftwaffe-boy** [SistemasTecTlaxiaco/cs-equipo-irving-1#1]
[Imagenes_Multpiples.pdf](https://github.com/SistemasTecTlaxiaco/cs-equipo-irving-1/files/15168369/Imagenes_Multpiples.pdf)

**Comment by JudithReynaCS** [comment]
EXCELENTE :) 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
